<?php

namespace App\Exports;


use App\Models\PengajuanDana;


use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;


use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;



class ApprovalSheet implements
FromCollection,
WithTitle,
WithStyles,
WithColumnWidths
{


    public function collection()
    {


        $requests = PengajuanDana::with([

            'pengguna',
            'proyek',
            'divisi',
            'penyetuju'

        ])

        ->whereIn(

            'status',

            [
                'approved',
                'rejected'
            ]

        )

        ->latest()

        ->get();








        $rows = collect([



            [
                '',
                'SAHABAT EKSPLORASI BANUA',
                '',
                '',
                '',
                '',
                ''
            ],



            [
                '',
                'FINANCIAL MANAGEMENT SYSTEM',
                '',
                '',
                '',
                '',
                ''
            ],



            [
                '',
                'LAPORAN APPROVAL DANA',
                date('d M Y'),
                '',
                '',
                '',
                ''
            ],



            [
                '',
                '',
                '',
                '',
                '',
                '',
                ''
            ],




            [
            'TANGGAL',
            'PEMOHON',
            'PROJECT',
            'DIVISI',
            'NOMINAL',
            'STATUS',
            'DISETUJUI OLEH',
            'CATATAN'
            ],

        ]);









        foreach($requests as $item)
        {


            $rows->push([



                optional($item->created_at)
                ->format('d M Y'),




                $item->pengguna->name ?? '-',




                $item->proyek->nama_proyek ?? '-',




                $item->divisi->nama_divisi ?? '-',




                $item->jumlah,




                ucfirst(
                    $item->status
                ),




                $item->penyetuju->name ?? '-',


                $item->catatan_persetujuan ?? '-'


            ]);


        }







        $rows->push([

            '',
            '',
            '',
            '',
            '',
            '',
            '',
            ''

        ]);








       $rows->push([

            'Generated by Sahabat Eksplorasi Banua Financial System',
            '',
            '',
            '',
            '',
            '',
            '',
            ''

        ]);







        return $rows;


    }









    public function title(): string
    {

        return 'Approval Dana';

    }









    public function styles(Worksheet $sheet)
    {



        /*
        |--------------------------------------------------------------------------
        | HEADER
        |--------------------------------------------------------------------------
        */


        $sheet->mergeCells('B1:H1');

        $sheet->mergeCells('B2:H2');

        $sheet->mergeCells('B3:H3');








        /*
        |--------------------------------------------------------------------------
        | TITLE STYLE
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('A5:H5')
        ->getFont()
        ->setBold(true)
        ->setSize(11)
        ->getColor()
        ->setARGB('FFFFFF');





        $sheet->getStyle('B2:H2')
        ->getFont()
        ->setBold(true)
        ->setSize(13)
        ->getColor()
        ->setARGB('1E3A5F');





        $sheet->getStyle('B3:C3')
        ->getFont()
        ->setItalic(true)
        ->getColor()
        ->setARGB('64748B');







        $sheet->getStyle('B1:H3')
        ->getAlignment()
        ->setHorizontal(
            Alignment::HORIZONTAL_CENTER
        );









        /*
        |--------------------------------------------------------------------------
        | TABLE HEADER
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('A5:H5')
        ->getFill()
        ->setFillType(
            Fill::FILL_SOLID
        )
        ->getStartColor()
        ->setARGB(
            '6B4F1D'
        );





        $sheet->getStyle('A5:H5')
        ->getFont()
        ->setBold(true)
        ->getColor()
        ->setARGB(
            'FFFFFF'
        );









        /*
        |--------------------------------------------------------------------------
        | TABLE BORDER
        |--------------------------------------------------------------------------
        */


        $highestRow = $sheet->getHighestRow();



        $sheet->getStyle(
            'A5:H'.$highestRow
        )
        ->getBorders()
        ->getAllBorders()
        ->setBorderStyle(
            Border::BORDER_THIN
        );









        /*
        |--------------------------------------------------------------------------
        | RUPIAH
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle(
            'E6:E'.$highestRow
        )
        ->getNumberFormat()
        ->setFormatCode(
            '"Rp" #,##0'
        );









        /*
        |--------------------------------------------------------------------------
        | STATUS COLOR
        |--------------------------------------------------------------------------
        */


        for($i=6;$i<=$highestRow;$i++)
        {


            $status = $sheet->getCell(
                'F'.$i
            )->getValue();




            if($status == 'Approved')
            {


                $sheet->getStyle(
                    'F'.$i
                )
                ->getFont()
                ->getColor()
                ->setARGB(
                    '16A34A'
                );


            }



            elseif($status == 'Rejected')
            {


                $sheet->getStyle(
                    'F'.$i
                )
                ->getFont()
                ->getColor()
                ->setARGB(
                    'DC2626'
                );


            }



        }









        /*
        |--------------------------------------------------------------------------
        | LOGO
        |--------------------------------------------------------------------------
        */


        $logo = public_path(
            'images/logo-cv.png'
        );



        if(file_exists($logo))
        {


            $drawing = new Drawing();


            $drawing->setName(
                'Logo SEB'
            );


            $drawing->setPath(
                $logo
            );


            $drawing->setHeight(
                55
            );


            $drawing->setCoordinates(
                'A1'
            );


            $drawing->setWorksheet(
                $sheet
            );


        }









        /*
        |--------------------------------------------------------------------------
        | FOOTER
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle(
            'A'.$highestRow
        )
        ->getFont()
        ->setItalic(true)
        ->getColor()
        ->setARGB(
            '64748B'
        );



        $sheet->getStyle(
            'H6:H'.$highestRow
        )
        ->getAlignment()
        ->setWrapText(true)
        ->setVertical(
        Alignment::VERTICAL_CENTER
        );



        $sheet->freezePane(
            'A6'
        );



        return $sheet;


    }








public function columnWidths(): array
{
    return [

        'A'=>14,

        'B'=>18,

        'C'=>20,

        'D'=>16,

        'E'=>16,

        'F'=>13,

        'G'=>22,

        'H'=>20,

    ];
}


}