<?php

namespace App\Exports;


use App\Models\SaldoDivisi;


use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithDrawings;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;


use Maatwebsite\Excel\Events\AfterSheet;


use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;



class BalanceSheet implements

    FromArray,

    WithEvents,

    WithDrawings,

    WithTitle,

    WithCustomStartCell

{


    protected $startDate;

    protected $endDate;



    public function __construct(
        $startDate = null,
        $endDate = null
    )
    {

        $this->startDate = $startDate;

        $this->endDate = $endDate;

    }





    public function title(): string
    {
        return 'Saldo Divisi';
    }





    public function startCell(): string
    {
        return 'A6';
    }






    public function array(): array
    {


        $data = SaldoDivisi::with([

            'divisi',
            'proyek'

        ])

        ->when(

            $this->startDate,

            function($query){

                $query->whereDate(
                    'created_at',
                    '>=',
                    $this->startDate
                );

            }

        )

        ->when(

            $this->endDate,

            function($query){

                $query->whereDate(
                    'created_at',
                    '<=',
                    $this->endDate
                );

            }

        )

        ->latest()

        ->get();





        $rows = [


            [
                '',
                '',
                '',
                ''
            ],


            [
                'INFORMASI SALDO DIVISI',
                '',
                '',
                ''
            ],


            [
                'Sistem',
                'Financial Management System',
                'Tanggal Cetak',
                now()->format('d M Y')
            ],


            [
                'Status Laporan',
                'Monitoring Saldo Divisi',
                'Total Data',
                $data->count().' Data'
            ],


            [
                'Ringkasan',
                'Informasi saldo setiap divisi',
                '',
                ''
            ],


            [
                'DIVISI',
                'PROJECT',
                'SALDO',
                'STATUS'
            ]

        ];








        foreach($data as $item)
        {


            $rows[]=[


                $item->divisi->nama_divisi ?? '-',


                $item->proyek->nama_proyek ?? '-',


                $item->saldo ?? 0,


                ($item->saldo > 0)
                ?
                'Aktif'
                :
                'Kosong'


            ];


        }







        $rows[]=[

            '',
            '',
            '',
            ''

        ];





        $rows[]=[

            'Generated by Sahabat Eksplorasi Banua Financial System',
            '',
            '',
            ''

        ];






        return $rows;


    }









    public function drawings()
    {


        $drawing = new Drawing();


        $drawing->setName(
            'Logo CV'
        );


        $drawing->setDescription(
            'Logo CV Sahabat Eksplorasi Banua'
        );


        $drawing->setPath(
            public_path(
                'images/logo-cv.png'
            )
        );


        $drawing->setHeight(
            70
        );


        $drawing->setCoordinates(
            'A1'
        );


        $drawing->setOffsetX(
            10
        );


        $drawing->setOffsetY(
            5
        );


        return $drawing;


    }









    public function registerEvents(): array
    {


        return [



            AfterSheet::class => function(AfterSheet $event){


                $sheet = $event
                    ->sheet
                    ->getDelegate();





                /*
                HEADER
                */


                $sheet->mergeCells('B1:D1');

                $sheet->mergeCells('B2:D2');

                $sheet->mergeCells('B3:D3');





                $sheet->setCellValue(
                    'B1',
                    'CV SAHABAT EKSPLORASI BANUA'
                );


                $sheet->setCellValue(
                    'B2',
                    'FINANCIAL MANAGEMENT SYSTEM'
                );


                $sheet->setCellValue(
                    'B3',
                    'LAPORAN SALDO DIVISI'
                );






                $sheet->getStyle('B1:D3')
                ->applyFromArray([


                    'font'=>[
                        'bold'=>true
                    ],


                    'alignment'=>[

                        'horizontal'=>Alignment::HORIZONTAL_CENTER,

                        'vertical'=>Alignment::VERTICAL_CENTER

                    ]


                ]);





                $sheet->getStyle('B1')
                ->getFont()
                ->setSize(16);



                $sheet->getStyle('B2')
                ->getFont()
                ->setSize(13);



                $sheet->getStyle('B3')
                ->getFont()
                ->setItalic(true);









                /*
                SECTION
                */


                $sheet->mergeCells(
                    'A7:D7'
                );



                $sheet->getStyle('A7:D7')
                ->applyFromArray([


                    'fill'=>[

                        'fillType'=>Fill::FILL_SOLID,

                        'startColor'=>[
                            'rgb'=>'000000'
                        ]

                    ],


                    'font'=>[

                        'bold'=>true,

                        'color'=>[
                            'rgb'=>'FFFFFF'
                        ]

                    ],


                    'alignment'=>[

                        'horizontal'=>Alignment::HORIZONTAL_CENTER

                    ]


                ]);









                /*
                TABLE HEADER
                */


                $sheet->getStyle(
                    'A11:D11'
                )
                ->applyFromArray([


                    'fill'=>[

                        'fillType'=>Fill::FILL_SOLID,

                        'startColor'=>[
                            'rgb'=>'000000'
                        ]

                    ],


                    'font'=>[

                        'bold'=>true,

                        'color'=>[
                            'rgb'=>'FFFFFF'
                        ]

                    ],


                    'alignment'=>[

                        'horizontal'=>Alignment::HORIZONTAL_CENTER

                    ]

                ]);









                $lastRow=$sheet->getHighestRow();







                /*
                BORDER
                */


                $sheet->getStyle(
                    'A11:D'.$lastRow
                )
                ->applyFromArray([


                    'borders'=>[

                        'allBorders'=>[

                            'borderStyle'=>Border::BORDER_THIN,

                            'color'=>[
                                'rgb'=>'D1D5DB'
                            ]

                        ]

                    ]

                ]);








                /*
                RUPIAH
                */


                $sheet->getStyle(
                    'C12:C'.$lastRow
                )
                ->getNumberFormat()
                ->setFormatCode(
                    '"Rp" #,##0'
                );









                /*
                STATUS
                */


                for($i=12;$i<=$lastRow;$i++)
                {


                    $sheet->getStyle(
                        'D'.$i
                    )
                    ->applyFromArray([


                        'fill'=>[

                            'fillType'=>Fill::FILL_SOLID,

                            'startColor'=>[
                                'rgb'=>'DCFCE7'
                            ]

                        ],


                        'font'=>[

                            'bold'=>true,

                            'color'=>[
                                'rgb'=>'15803D'
                            ]

                        ]

                    ]);


                }








                /*
                WIDTH
                */


                $width=[

                    'A'=>22,

                    'B'=>35,

                    'C'=>22,

                    'D'=>18

                ];



                foreach($width as $col=>$size)
                {

                    $sheet->getColumnDimension($col)
                    ->setWidth($size);

                }









                $sheet->getRowDimension(1)
                ->setRowHeight(45);


                $sheet->getRowDimension(2)
                ->setRowHeight(30);


                $sheet->getRowDimension(11)
                ->setRowHeight(25);








                $sheet->freezePane(
                    'A12'
                );


            }


        ];

    }


}