<?php

namespace App\Exports;


use App\Models\SaldoDivisi;


use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;


use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;



class BalanceSheet implements
FromCollection,
WithTitle,
WithStyles,
WithColumnWidths
{


    public function collection()
    {


        $balances = SaldoDivisi::with([

            'proyek',

            'divisi'

        ])

        ->latest()

        ->get();






        $rows = collect([



            [
                '',
                'SAHABAT EKSPLORASI BANUA',
                '',
                '',
                ''
            ],



            [
                '',
                'FINANCIAL MANAGEMENT SYSTEM',
                '',
                '',
                ''
            ],



            [
                '',
                'LAPORAN SALDO DIVISI',
                date('d M Y'),
                '',
                ''
            ],




            [
                '',
                '',
                '',
                '',
                ''
            ],




            [
                'PROJECT',
                'DIVISI',
                'SALDO',
                'STATUS',
                ''
            ],



        ]);








        foreach($balances as $balance)
        {


            $rows->push([



                $balance->proyek->nama_proyek ?? '-',



                $balance->divisi->nama_divisi ?? '-',



                $balance->saldo,



                $balance->saldo > 0

                ?

                'Tersedia'

                :

                'Kosong',



                ''



            ]);


        }








        $rows->push([

            '',
            '',
            '',
            '',
            ''

        ]);







        $rows->push([

            'Generated by Sahabat Eksplorasi Banua Financial System',

            '',
            '',
            '',
            ''

        ]);






        return $rows;


    }









    public function title(): string
    {

        return 'Saldo Divisi';

    }









    public function styles(Worksheet $sheet)
    {



        /*
        |--------------------------------------------------------------------------
        | HEADER
        |--------------------------------------------------------------------------
        */


        $sheet->mergeCells('B1:E1');

        $sheet->mergeCells('B2:E2');

        $sheet->mergeCells('B3:C3');







        /*
        |--------------------------------------------------------------------------
        | TITLE
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('B1:E1')
        ->getFont()
        ->setBold(true)
        ->setSize(18)
        ->getColor()
        ->setARGB('6B4F1D');




        $sheet->getStyle('B2:E2')
        ->getFont()
        ->setBold(true)
        ->setSize(13)
        ->getColor()
        ->setARGB('1E3A5F');




        $sheet->getStyle('B3:C3')
        ->getFont()
        ->setItalic(true)
        ->getColor()
        ->setARGB('64748B');






        $sheet->getStyle('B1:E3')
        ->getAlignment()
        ->setHorizontal(
            Alignment::HORIZONTAL_CENTER
        );









        /*
        |--------------------------------------------------------------------------
        | TABLE HEADER
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('A5:D5')
        ->getFill()
        ->setFillType(
            Fill::FILL_SOLID
        )
        ->getStartColor()
        ->setARGB(
            '6B4F1D'
        );




        $sheet->getStyle('A5:D5')
        ->getFont()
        ->setBold(true)
        ->getColor()
        ->setARGB(
            'FFFFFF'
        );








        /*
        |--------------------------------------------------------------------------
        | TABLE
        |--------------------------------------------------------------------------
        */


        $highestRow = $sheet->getHighestRow();



        $sheet->getStyle(
            'A5:D'.$highestRow
        )
        ->getBorders()
        ->getAllBorders()
        ->setBorderStyle(
            Border::BORDER_THIN
        );







        /*
        |--------------------------------------------------------------------------
        | RUPIAH
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle(
            'C6:C'.$highestRow
        )
        ->getNumberFormat()
        ->setFormatCode(
            '"Rp" #,##0'
        );








        /*
        |--------------------------------------------------------------------------
        | STATUS
        |--------------------------------------------------------------------------
        */


        for($i=6;$i<=$highestRow;$i++)
        {


            $status = $sheet->getCell(
                'D'.$i
            )->getValue();



            if($status == 'Tersedia')
            {


                $sheet->getStyle(
                    'D'.$i
                )
                ->getFont()
                ->getColor()
                ->setARGB(
                    '16A34A'
                );


            }
            else
            {


                $sheet->getStyle(
                    'D'.$i
                )
                ->getFont()
                ->getColor()
                ->setARGB(
                    'DC2626'
                );


            }


        }









        /*
        |--------------------------------------------------------------------------
        | LOGO
        |--------------------------------------------------------------------------
        */


        $logo = public_path(
            'images/logo-cv.png'
        );



        if(file_exists($logo))
        {


            $drawing = new Drawing();


            $drawing->setName(
                'Logo SEB'
            );



            $drawing->setPath(
                $logo
            );



            $drawing->setHeight(
                55
            );



            $drawing->setCoordinates(
                'A1'
            );



            $drawing->setWorksheet(
                $sheet
            );


        }









        /*
        |--------------------------------------------------------------------------
        | FOOTER
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle(
            'A'.$highestRow
        )
        ->getFont()
        ->setItalic(true)
        ->getColor()
        ->setARGB(
            '64748B'
        );







        $sheet->freezePane(
            'A6'
        );



        return $sheet;


    }









    public function columnWidths(): array
    {


        return [

            'A'=>30,

            'B'=>25,

            'C'=>22,

            'D'=>18,

            'E'=>15,

        ];


    }



}