<?php

namespace App\Exports;


use App\Models\RekeningBank;
use App\Models\SetoranProyek;
use App\Models\TransaksiDana;


use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithDrawings;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;


use Maatwebsite\Excel\Events\AfterSheet;


use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;



class BankBalanceSheet implements

    FromArray,

    WithEvents,

    WithDrawings,

    WithTitle,

    WithCustomStartCell

{


    protected $startDate;

    protected $endDate;



    public function __construct(
        $startDate=null,
        $endDate=null
    )
    {

        $this->startDate=$startDate;

        $this->endDate=$endDate;

    }







    public function title(): string
    {

        return 'Saldo Bank';

    }







    public function startCell(): string
    {

        return 'A6';

    }









    public function array(): array
    {


        $rekening = RekeningBank::get();



        $data = collect();







        foreach($rekening as $bank)
        {


            $masuk = SetoranProyek::where(

                'rekening_bank_id',

                $bank->id

            )

            ->when(

                $this->startDate,

                function($query){

                    $query->whereDate(

                        'created_at',

                        '>=',

                        $this->startDate

                    );

                }

            )

            ->when(

                $this->endDate,

                function($query){

                    $query->whereDate(

                        'created_at',

                        '<=',

                        $this->endDate

                    );

                }

            )

            ->sum(
                'jumlah_setoran'
            );







            $keluar = TransaksiDana::where(

                'rekening_bank_id',

                $bank->id

            )

            ->when(

                $this->startDate,

                function($query){

                    $query->whereDate(

                        'created_at',

                        '>=',

                        $this->startDate

                    );

                }

            )

            ->when(

                $this->endDate,

                function($query){

                    $query->whereDate(

                        'created_at',

                        '<=',

                        $this->endDate

                    );

                }

            )

            ->sum(
                'jumlah'
            );







$data->push([


    'nama_bank'=>$bank->nama_bank ?? '-',


    'nomor_rekening'=>$bank->nomor_rekening ?? '-',


    'saldo_awal'=>$bank->saldo ?? 0,


    'mutasi'=>$masuk-$keluar,


    'saldo_akhir'=>($bank->saldo ?? 0)+($masuk-$keluar)


]);


        }









        $rows=[



            [

                '',

                '',

                '',

                '',

                ''

            ],




            [

                'INFORMASI SALDO BANK',

                '',

                '',

                '',

                ''

            ],




            [

                'Sistem',

                'Financial Management System',

                'Tanggal Cetak',

                now()->format('d M Y'),

                ''

            ],




            [

                'Status Laporan',

                'Monitoring Saldo Rekening Bank',

                'Total Bank',

                $data->count().' Rekening',

                ''

            ],




            [

                'Ringkasan',

                'Informasi saldo rekening perusahaan',

                '',

                '',

                ''

            ],





            [

                'BANK',

                'NOMOR REKENING',

                'SALDO AWAL',

                'MUTASI',

                'SALDO AKHIR'

            ]

        ];









        foreach($data as $item)
        {


            $rows[]=[



                $item['nama_bank'],



                $item['nomor_rekening'],



                $item['saldo_awal'],



                $item['mutasi'],



                $item['saldo_akhir']



            ];


        }









        $rows[]=[

            '',

            '',

            '',

            '',

            ''

        ];








        $rows[]=[

            'Generated by Sahabat Eksplorasi Banua Financial System',

            '',

            '',

            '',

            ''

        ];








        return $rows;


    }









    public function drawings()
    {


        $drawing = new Drawing();



        $drawing->setName(
            'Logo CV'
        );



        $drawing->setDescription(
            'Logo CV Sahabat Eksplorasi Banua'
        );



        $drawing->setPath(
            public_path(
                'images/logo-cv.png'
            )
        );



        $drawing->setHeight(
            70
        );



        $drawing->setCoordinates(
            'A1'
        );



        $drawing->setOffsetX(
            10
        );



        $drawing->setOffsetY(
            5
        );



        return $drawing;


    }









    public function registerEvents(): array
    {


        return [



            AfterSheet::class => function(AfterSheet $event){



                $sheet=$event
                    ->sheet
                    ->getDelegate();









                /*
                HEADER
                */


                $sheet->mergeCells('B1:E1');

                $sheet->mergeCells('B2:E2');

                $sheet->mergeCells('B3:E3');





                $sheet->setCellValue(
                    'B1',
                    'CV SAHABAT EKSPLORASI BANUA'
                );





                $sheet->setCellValue(
                    'B2',
                    'FINANCIAL MANAGEMENT SYSTEM'
                );





                $sheet->setCellValue(
                    'B3',
                    'LAPORAN SALDO BANK'
                );









                $sheet->getStyle('B1:E3')
                ->applyFromArray([



                    'font'=>[

                        'bold'=>true

                    ],



                    'alignment'=>[

                        'horizontal'=>Alignment::HORIZONTAL_CENTER,

                        'vertical'=>Alignment::VERTICAL_CENTER

                    ]



                ]);








                $sheet->getStyle('B1')
                ->getFont()
                ->setSize(16);



                $sheet->getStyle('B2')
                ->getFont()
                ->setSize(13);



                $sheet->getStyle('B3')
                ->getFont()
                ->setItalic(true);









                /*
                SECTION
                */


                $sheet->mergeCells(
                    'A7:E7'
                    
                );



                $sheet->getStyle('A7:E7')
                ->applyFromArray([



                    'fill'=>[

                        'fillType'=>Fill::FILL_SOLID,

                        'startColor'=>[

                            'rgb'=>'000000'

                        ]

                    ],



                    'font'=>[

                        'bold'=>true,

                        'color'=>[

                            'rgb'=>'FFFFFF'

                        ]

                    ],



                    'alignment'=>[

                        'horizontal'=>Alignment::HORIZONTAL_CENTER

                    ]



                ]);









                /*
                TABLE HEADER
                */

 $sheet->getStyle('A11:E11')
->applyFromArray([

    'fill'=>[

        'fillType'=>Fill::FILL_SOLID,

        'startColor'=>[
            'rgb'=>'000000'
        ]

    ],

    'font'=>[

        'bold'=>true,

        'color'=>[
            'rgb'=>'FFFFFF'
        ]

    ],

    'alignment'=>[

        'horizontal'=>Alignment::HORIZONTAL_CENTER,

        'vertical'=>Alignment::VERTICAL_CENTER

    ]

]);





                $lastRow=$sheet->getHighestRow();









                    $sheet->getStyle(
                        'A11:E'.$lastRow
                    )
                ->applyFromArray([



                    'borders'=>[



                        'allBorders'=>[

                            'borderStyle'=>Border::BORDER_THIN,

                            'color'=>[

                                'rgb'=>'D1D5DB'

                            ]

                        ]



                    ]



                            ]);









                /*
                FORMAT RUPIAH
                */


                $sheet->getStyle(
                    'C12:E'.$lastRow
                )
                ->getNumberFormat()
                ->setFormatCode(
                    '"Rp" #,##0'
                );
                $sheet->getStyle(
    'E12:E'.$lastRow
)
->applyFromArray([


    'fill'=>[

        'fillType'=>Fill::FILL_SOLID,

        'startColor'=>[
            'rgb'=>'DCFCE7'
        ]

    ],


    'font'=>[

        'bold'=>true,

        'color'=>[
            'rgb'=>'15803D'
        ]

    ]

]);



$sheet->getStyle(
    'C12:E'.$lastRow
)
->getAlignment()
->setHorizontal(
    Alignment::HORIZONTAL_CENTER
);





                /*
                WIDTH
                */


                $width=[

                    'A'=>25,

                    'B'=>25,

                    'C'=>22,

                    'D'=>22,

                    'E'=>22

                ];



                foreach($width as $col=>$size)
                {

                    $sheet->getColumnDimension($col)
                    ->setWidth($size);

                }









                /*
                HEIGHT
                */


                $sheet->getRowDimension(1)
                ->setRowHeight(45);



                $sheet->getRowDimension(2)
                ->setRowHeight(30);



                $sheet->getRowDimension(11)
                ->setRowHeight(25);









                $sheet->freezePane(
                    'A12'
                );



            }


        ];

    }


}