<?php

namespace App\Exports;


use App\Models\SetoranProyek;
use App\Models\TransaksiDana;
use App\Models\Proyek;
use App\Models\RekeningBank;


use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;


use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;



class DashboardSheet implements
FromCollection,
WithTitle,
WithStyles,
WithColumnWidths
{


    public function collection()
    {


        $income = SetoranProyek::sum(
            'jumlah_setoran'
        );


        $expense = TransaksiDana::sum(
            'jumlah'
        );


        $balance = $income - $expense;



        $bankBalance = RekeningBank::where(
            'status',
            true
        )
        ->sum('saldo');



        $bankCount = RekeningBank::where(
            'status',
            true
        )
        ->count();



        $projectCount = Proyek::count();



        $transactionCount =
            SetoranProyek::count()
            +
            TransaksiDana::count();





        return collect([


            [
                '',
                'SAHABAT EKSPLORASI BANUA',
                '',
                '',
                ''
            ],


            [
                '',
                'FINANCIAL MANAGEMENT SYSTEM',
                '',
                '',
                ''
            ],


            [
                '',
                'LAPORAN DASHBOARD KEUANGAN',
                date('d M Y'),
                '',
                ''
            ],


            [
                '',
                '',
                '',
                '',
                ''
            ],



            [
                'RINGKASAN KEUANGAN',
                '',
                '',
                '',
                ''
            ],



            [
                'Total Pemasukan',
                $income,
                'Dana Masuk',
                '',
                ''
            ],



            [
                'Total Pengeluaran',
                $expense,
                'Dana Keluar',
                '',
                ''
            ],



            [
                'Saldo Akhir',
                $balance,
                'Dana Tersedia',
                '',
                ''
            ],



            [
                'Saldo Bank',
                $bankBalance,
                'Rekening Aktif',
                '',
                ''
            ],



            [
                'Jumlah Rekening',
                $bankCount,
                'Bank Aktif',
                '',
                ''
            ],



            [
                'Jumlah Project',
                $projectCount,
                'Project Aktif',
                '',
                ''
            ],



            [
                'Jumlah Transaksi',
                $transactionCount,
                'Total Transaksi',
                '',
                ''
            ],


            [
                '',
                '',
                '',
                '',
                ''
            ],



            [
                'Generated by Sahabat Eksplorasi Banua Financial System',
                '',
                '',
                '',
                ''
            ],


        ]);


    }







    public function title(): string
    {

        return 'Dashboard';

    }









    public function styles(Worksheet $sheet)
    {



        /*
        |--------------------------------------------------------------------------
        | MERGE HEADER
        |--------------------------------------------------------------------------
        */


        $sheet->mergeCells('B1:E1');

        $sheet->mergeCells('B2:E2');

        $sheet->mergeCells('B3:C3');

        $sheet->mergeCells('A5:C5');

        $sheet->mergeCells('A14:E14');






        /*
        |--------------------------------------------------------------------------
        | HEADER COMPANY
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('B1:E1')
        ->getFont()
        ->setBold(true)
        ->setSize(18)
        ->getColor()
        ->setARGB('6B4F1D');



        $sheet->getStyle('B2:E2')
        ->getFont()
        ->setBold(true)
        ->setSize(13)
        ->getColor()
        ->setARGB('1E3A5F');



        $sheet->getStyle('B3:C3')
        ->getFont()
        ->setItalic(true)
        ->getColor()
        ->setARGB('64748B');





        $sheet->getStyle('B1:E3')
        ->getAlignment()
        ->setHorizontal(
            Alignment::HORIZONTAL_CENTER
        );







        /*
        |--------------------------------------------------------------------------
        | SECTION TITLE
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('A5:C5')
        ->getFill()
        ->setFillType(
            Fill::FILL_SOLID
        )
        ->getStartColor()
        ->setARGB(
            '6B4F1D'
        );



        $sheet->getStyle('A5:C5')
        ->getFont()
        ->setBold(true)
        ->getColor()
        ->setARGB(
            'FFFFFF'
        );







        /*
        |--------------------------------------------------------------------------
        | DATA
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('A6:C12')
        ->getBorders()
        ->getAllBorders()
        ->setBorderStyle(
            Border::BORDER_THIN
        );



        $sheet->getStyle('A6:A12')
        ->getFont()
        ->setBold(true);



        $sheet->getStyle('B6:B9')
        ->getNumberFormat()
        ->setFormatCode(
            '"Rp" #,##0'
        );





        /*
        |--------------------------------------------------------------------------
        | STATUS COLOR
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('C6')
        ->getFont()
        ->getColor()
        ->setARGB('16A34A');



        $sheet->getStyle('C7')
        ->getFont()
        ->getColor()
        ->setARGB('DC2626');



        $sheet->getStyle('C8')
        ->getFont()
        ->getColor()
        ->setARGB('6B4F1D');






        /*
        |--------------------------------------------------------------------------
        | FOOTER
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('A14:E14')
        ->getFont()
        ->setItalic(true)
        ->setSize(10)
        ->getColor()
        ->setARGB('64748B');






        /*
        |--------------------------------------------------------------------------
        | LOGO
        |--------------------------------------------------------------------------
        */


        $logo = public_path(
            'images/logo-cv.png'
        );


        if(file_exists($logo))
        {


            $drawing = new Drawing();


            $drawing->setName(
                'Logo SEB'
            );


            $drawing->setDescription(
                'Sahabat Eksplorasi Banua'
            );


            $drawing->setPath(
                $logo
            );


            $drawing->setHeight(
                55
            );


            $drawing->setCoordinates(
                'A1'
            );


            $drawing->setWorksheet(
                $sheet
            );

        }






        $sheet->freezePane('A6');



        return $sheet;


    }







    public function columnWidths(): array
    {


        return [

            'A'=>30,

            'B'=>25,

            'C'=>22,

            'D'=>15,

            'E'=>15,

        ];


    }


}