<?php

namespace App\Exports;


use App\Models\TransaksiDana;


use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;


use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;



class ExpenseSheet implements
FromCollection,
WithTitle,
WithStyles,
WithColumnWidths
{


    public function collection()
    {


        $data = TransaksiDana::with([

            'pengajuanDana.proyek',
            'pengajuanDana.divisi',
            'pengajuanDana.pengguna',
            'penyetuju',
            'rekeningBank'

        ])

        ->latest()

        ->get();






        $rows = collect([



            [
                '',
                'SAHABAT EKSPLORASI BANUA',
                '',
                '',
                '',
                ''
            ],



            [
                '',
                'FINANCIAL MANAGEMENT SYSTEM',
                '',
                '',
                '',
                ''
            ],



            [
                '',
                'LAPORAN PENGELUARAN DANA',
                date('d M Y'),
                '',
                '',
                ''
            ],



            [
                '',
                '',
                '',
                '',
                '',
                ''
            ],




            [
                'TANGGAL',
                'PEMOHON',
                'PROJECT',
                'DIVISI',
                'NOMINAL',
                'STATUS'
            ],


        ]);









        foreach($data as $item)
        {


            $rows->push([



                \Carbon\Carbon::parse(
                    $item->tanggal
                )
                ->format('d M Y'),




                $item->pengajuanDana->pengguna->name ?? '-',




                $item->pengajuanDana->proyek->nama_proyek ?? '-',




                $item->pengajuanDana->divisi->nama_divisi ?? '-',





                $item->jumlah,





                $item->pengajuanDana->status ?? 'Approved'



            ]);


        }






        $rows->push([

            '',
            '',
            '',
            '',
            '',
            ''

        ]);






        $rows->push([

            'Generated by Sahabat Eksplorasi Banua Financial System',

            '',
            '',
            '',
            '',
            ''

        ]);






        return $rows;


    }








    public function title(): string
    {

        return 'Pengeluaran';

    }









    public function styles(Worksheet $sheet)
    {


        /*
        |--------------------------------------------------------------------------
        | HEADER MERGE
        |--------------------------------------------------------------------------
        */


        $sheet->mergeCells('B1:F1');

        $sheet->mergeCells('B2:F2');

        $sheet->mergeCells('B3:C3');







        /*
        |--------------------------------------------------------------------------
        | TITLE STYLE
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('B1:F1')
        ->getFont()
        ->setBold(true)
        ->setSize(18)
        ->getColor()
        ->setARGB('6B4F1D');




        $sheet->getStyle('B2:F2')
        ->getFont()
        ->setBold(true)
        ->setSize(13)
        ->getColor()
        ->setARGB('1E3A5F');




        $sheet->getStyle('B3:C3')
        ->getFont()
        ->setItalic(true)
        ->getColor()
        ->setARGB('64748B');






        $sheet->getStyle('B1:F3')
        ->getAlignment()
        ->setHorizontal(
            Alignment::HORIZONTAL_CENTER
        );







        /*
        |--------------------------------------------------------------------------
        | TABLE HEADER
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle('A5:F5')
        ->getFill()
        ->setFillType(
            Fill::FILL_SOLID
        )
        ->getStartColor()
        ->setARGB(
            '6B4F1D'
        );




        $sheet->getStyle('A5:F5')
        ->getFont()
        ->setBold(true)
        ->getColor()
        ->setARGB(
            'FFFFFF'
        );








        /*
        |--------------------------------------------------------------------------
        | TABLE BORDER
        |--------------------------------------------------------------------------
        */


        $highestRow = $sheet->getHighestRow();



        $sheet->getStyle(
            'A5:F'.$highestRow
        )
        ->getBorders()
        ->getAllBorders()
        ->setBorderStyle(
            Border::BORDER_THIN
        );








        /*
        |--------------------------------------------------------------------------
        | FORMAT RUPIAH
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle(
            'E6:E'.$highestRow
        )
        ->getNumberFormat()
        ->setFormatCode(
            '"Rp" #,##0'
        );








        /*
        |--------------------------------------------------------------------------
        | STATUS COLOR
        |--------------------------------------------------------------------------
        */


        for($i=6;$i<=$highestRow;$i++)
        {


            $status = $sheet->getCell(
                'F'.$i
            )->getValue();



            if($status == 'approved')
            {


                $sheet->getStyle(
                    'F'.$i
                )
                ->getFont()
                ->getColor()
                ->setARGB(
                    '16A34A'
                );


            }



            elseif($status == 'rejected')
            {


                $sheet->getStyle(
                    'F'.$i
                )
                ->getFont()
                ->getColor()
                ->setARGB(
                    'DC2626'
                );


            }



        }









        /*
        |--------------------------------------------------------------------------
        | LOGO
        |--------------------------------------------------------------------------
        */


        $logo = public_path(
            'images/logo-cv.png'
        );



        if(file_exists($logo))
        {


            $drawing = new Drawing();


            $drawing->setName(
                'Logo SEB'
            );



            $drawing->setPath(
                $logo
            );



            $drawing->setHeight(
                55
            );



            $drawing->setCoordinates(
                'A1'
            );



            $drawing->setWorksheet(
                $sheet
            );


        }









        /*
        |--------------------------------------------------------------------------
        | FOOTER
        |--------------------------------------------------------------------------
        */


        $sheet->getStyle(
            'A'.$highestRow
        )
        ->getFont()
        ->setItalic(true)
        ->getColor()
        ->setARGB(
            '64748B'
        );






        $sheet->freezePane(
            'A6'
        );



        return $sheet;


    }









    public function columnWidths(): array
    {

        return [

            'A'=>18,

            'B'=>25,

            'C'=>28,

            'D'=>22,

            'E'=>22,

            'F'=>18,

        ];


    }


}