<?php

namespace App\Exports;


use App\Models\TransaksiDana;


use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithDrawings;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;


use Maatwebsite\Excel\Events\AfterSheet;


use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;



class ExpenseSheet implements

    FromArray,

    WithEvents,

    WithDrawings,

    WithTitle,

    WithCustomStartCell

{


    protected $startDate;

    protected $endDate;



    public function __construct(
        $startDate = null,
        $endDate = null
    )
    {

        $this->startDate = $startDate;

        $this->endDate = $endDate;

    }







    public function title(): string
    {

        return 'Pengeluaran';

    }







    public function startCell(): string
    {

        return 'A6';

    }








    public function array(): array
    {


        $data = TransaksiDana::with([

            'pengajuanDana.proyek',

            'rekeningBank'

        ])

        ->when(

            $this->startDate,

            function($query){

                $query->whereDate(

                    'created_at',

                    '>=',

                    $this->startDate

                );

            }

        )

        ->when(

            $this->endDate,

            function($query){

                $query->whereDate(

                    'created_at',

                    '<=',

                    $this->endDate

                );

            }

        )

        ->latest()

        ->get();








        $rows = [


            [

                '',

                '',

                '',

                '',

                ''

            ],




            [

                'INFORMASI PENGELUARAN',

                '',

                '',

                '',

                ''

            ],




            [

                'Sistem',

                'Financial Management System',

                'Tanggal Cetak',

                now()->format('d M Y'),

                ''

            ],




            [

                'Status Laporan',

                'Pengeluaran Operasional',

                'Total Data',

                $data->count().' Transaksi',

                ''

            ],




            [

                'Ringkasan',

                'Monitoring penggunaan dana perusahaan',

                '',

                '',

                ''

            ],




            [

                'TANGGAL',

                'PROJECT',

                'BANK',

                'NOMINAL',

                'STATUS'

            ]

        ];








        foreach($data as $item)
        {


            $rows[] = [


                optional(
                    $item->created_at
                )
                ->format('d M Y'),




                $item->pengajuanDana->proyek->nama_proyek ?? '-',



                $item->rekeningBank->nama_bank ?? '-',



                $item->jumlah ?? 0,



                'Pengeluaran'


            ];


        }








        $rows[] = [

            '',

            '',

            '',

            '',

            ''

        ];








        $rows[] = [

            'Generated by Sahabat Eksplorasi Banua Financial System',

            '',

            '',

            '',

            ''

        ];








        return $rows;


    }









    public function drawings()
    {


        $drawing = new Drawing();



        $drawing->setName(
            'Logo CV'
        );



        $drawing->setDescription(
            'Logo CV Sahabat Eksplorasi Banua'
        );



        $drawing->setPath(
            public_path(
                'images/logo-cv.png'
            )
        );



        $drawing->setHeight(
            70
        );



        $drawing->setCoordinates(
            'A1'
        );



        $drawing->setOffsetX(
            10
        );



        $drawing->setOffsetY(
            5
        );



        return $drawing;


    }

        public function registerEvents(): array
    {


        return [


            AfterSheet::class => function(AfterSheet $event){


                $sheet = $event
                    ->sheet
                    ->getDelegate();





                /*
                HEADER PERUSAHAAN
                */


                $sheet->mergeCells('B1:E1');

                $sheet->mergeCells('B2:E2');

                $sheet->mergeCells('B3:E3');





                $sheet->setCellValue(
                    'B1',
                    'CV SAHABAT EKSPLORASI BANUA'
                );



                $sheet->setCellValue(
                    'B2',
                    'FINANCIAL MANAGEMENT SYSTEM'
                );



                $sheet->setCellValue(
                    'B3',
                    'LAPORAN PENGELUARAN'
                );








                $sheet->getStyle(
                    'B1:E3'
                )
                ->applyFromArray([


                    'font'=>[

                        'bold'=>true

                    ],


                    'alignment'=>[

                        'horizontal'=>Alignment::HORIZONTAL_CENTER,

                        'vertical'=>Alignment::VERTICAL_CENTER

                    ]


                ]);






                $sheet->getStyle('B1')
                    ->getFont()
                    ->setSize(16)
                    ->setColor(
                        new \PhpOffice\PhpSpreadsheet\Style\Color('000000')
                    );



                $sheet->getStyle('B2')
                    ->getFont()
                    ->setSize(13)
                    ->setColor(
                        new \PhpOffice\PhpSpreadsheet\Style\Color('000000')
                    );



                $sheet->getStyle('B3')
                    ->getFont()
                    ->setItalic(true)
                    ->setSize(10)
                    ->setColor(
                        new \PhpOffice\PhpSpreadsheet\Style\Color('64748B')
                    );









                /*
                SECTION HEADER
                */


                $sheet->mergeCells(
                    'A7:E7'
                );



                $sheet->getStyle(
                    'A7:E7'
                )
                ->applyFromArray([


                    'fill'=>[

                        'fillType'=>Fill::FILL_SOLID,

                        'startColor'=>[

                            'rgb'=>'000000'

                        ]

                    ],



                    'font'=>[

                        'bold'=>true,

                        'color'=>[

                            'rgb'=>'FFFFFF'

                        ]

                    ],



                    'alignment'=>[

                        'horizontal'=>Alignment::HORIZONTAL_CENTER,

                        'vertical'=>Alignment::VERTICAL_CENTER

                    ]


                ]);









                /*
                TABLE HEADER
                */


                $sheet->getStyle(
                    'A11:E11'
                )
                ->applyFromArray([


                    'fill'=>[

                        'fillType'=>Fill::FILL_SOLID,

                        'startColor'=>[

                            'rgb'=>'000000'

                        ]

                    ],



                    'font'=>[

                        'bold'=>true,

                        'color'=>[

                            'rgb'=>'FFFFFF'

                        ]

                    ],



                    'alignment'=>[

                        'horizontal'=>Alignment::HORIZONTAL_CENTER,

                        'vertical'=>Alignment::VERTICAL_CENTER

                    ]


                ]);









                $lastRow = $sheet->getHighestRow();









                /*
                BORDER
                */


                $sheet->getStyle(
                    'A7:E'.$lastRow
                )
                ->applyFromArray([


                    'borders'=>[


                        'allBorders'=>[

                            'borderStyle'=>Border::BORDER_THIN,

                            'color'=>[

                                'rgb'=>'D1D5DB'

                            ]

                        ]

                    ]


                ]);









                $sheet->getStyle(
                    'A7:E'.$lastRow
                )
                ->getAlignment()
                ->setVertical(
                    Alignment::VERTICAL_CENTER
                );









                /*
                LABEL BOLD
                */


                foreach(['A','C'] as $column)
                {


                    $sheet->getStyle(
                        $column.'8:'.$column.$lastRow
                    )
                    ->getFont()
                    ->setBold(true);


                }









                /*
                FORMAT RUPIAH
                */


                $sheet->getStyle(
                    'D12:D'.$lastRow
                )
                ->getNumberFormat()
                ->setFormatCode(
                    '"Rp" #,##0'
                );









                /*
                STATUS COLOR
                */


                for(
                    $i = 12;
                    $i <= $lastRow;
                    $i++
                )
                {


                    $sheet->getStyle(
                        'E'.$i
                    )
                    ->applyFromArray([


                        'fill'=>[

                            'fillType'=>Fill::FILL_SOLID,

                            'startColor'=>[

                                'rgb'=>'FEE2E2'

                            ]

                        ],


                        'font'=>[

                            'bold'=>true,

                            'color'=>[

                                'rgb'=>'DC2626'

                            ]

                        ]

                    ]);


                }









                /*
                COLUMN WIDTH
                */


                $width = [


                    'A'=>18,

                    'B'=>35,

                    'C'=>25,

                    'D'=>22,

                    'E'=>18


                ];



                foreach($width as $column=>$size)
                {


                    $sheet->getColumnDimension($column)
                    ->setWidth($size);


                }









                /*
                ROW HEIGHT
                */


                $sheet->getRowDimension(1)
                    ->setRowHeight(45);



                $sheet->getRowDimension(2)
                    ->setRowHeight(30);



                $sheet->getRowDimension(7)
                    ->setRowHeight(25);



                $sheet->getRowDimension(11)
                    ->setRowHeight(25);









                /*
                FREEZE
                */


                $sheet->freezePane(
                    'A12'
                );



            }


        ];

    }


}