<?php

namespace App\Exports;


use App\Models\SetoranProyek;


use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithDrawings;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;


use Maatwebsite\Excel\Events\AfterSheet;


use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;



class IncomeSheet implements

    FromArray,

    WithEvents,

    WithDrawings,

    WithTitle,

    WithCustomStartCell

{


    protected $startDate;

    protected $endDate;



    public function __construct(
        $startDate=null,
        $endDate=null
    )
    {

        $this->startDate=$startDate;

        $this->endDate=$endDate;

    }






    public function title(): string
    {

        return 'Dana Masuk';

    }






    public function startCell(): string
    {

        return 'A6';

    }









    public function array(): array
    {


        $data = SetoranProyek::with([

            'proyek',
            'rekeningBank'

        ])

        ->when(

            $this->startDate,

            function($query){

                $query->whereDate(

                    'created_at',

                    '>=',

                    $this->startDate

                );

            }

        )

        ->when(

            $this->endDate,

            function($query){

                $query->whereDate(

                    'created_at',

                    '<=',

                    $this->endDate

                );

            }

        )

        ->latest()

        ->get();







        $rows = [



            [

                '',
                '',
                '',
                '',
                ''

            ],



            [

                'INFORMASI DANA MASUK',

                '',

                '',

                '',

                ''

            ],



            [

                'Sistem',

                'Financial Management System',

                'Tanggal Cetak',

                now()->format('d M Y'),

                ''

            ],



            [

                'Status Laporan',

                'Dana Masuk Project',

                'Total Data',

                $data->count().' Transaksi',

                ''

            ],



            [

                'Ringkasan',

                'Dana masuk project perusahaan',

                '',

                '',

                ''

            ],



            [

                'TANGGAL',

                'PROJECT',

                'BANK',

                'NOMINAL',

                'STATUS'

            ]



        ];









        foreach($data as $item)
        {


            $rows[]=[


                \Carbon\Carbon::parse(
                    $item->tanggal_setoran
                )
                ->format('d M Y'),



                $item->proyek->nama_proyek ?? '-',



                $item->rekeningBank->nama_bank ?? '-',



                $item->jumlah_setoran ?? 0,



                'Dana Masuk'


            ];


        }








        $rows[]=[

            '',

            '',

            '',

            '',

            ''

        ];





        $rows[]=[

            'Generated by Sahabat Eksplorasi Banua Financial System',

            '',

            '',

            '',

            ''

        ];






        return $rows;


    }









    public function drawings()
    {


        $drawing = new Drawing();



        $drawing->setName(
            'Logo CV'
        );



        $drawing->setDescription(
            'Logo Sahabat Eksplorasi Banua'
        );



        $drawing->setPath(
            public_path(
                'images/logo-cv.png'
            )
        );



        $drawing->setHeight(
            70
        );



        $drawing->setCoordinates(
            'A1'
        );



        $drawing->setOffsetX(
            10
        );



        $drawing->setOffsetY(
            5
        );



        return $drawing;


    }









    public function registerEvents(): array
    {


        return [



            AfterSheet::class => function(AfterSheet $event){


                $sheet=$event
                    ->sheet
                    ->getDelegate();








                /*
                HEADER
                */


                $sheet->mergeCells(
                    'B1:E1'
                );


                $sheet->mergeCells(
                    'B2:E2'
                );


                $sheet->mergeCells(
                    'B3:E3'
                );




                $sheet->setCellValue(
                    'B1',
                    'CV SAHABAT EKSPLORASI BANUA'
                );



                $sheet->setCellValue(
                    'B2',
                    'FINANCIAL MANAGEMENT SYSTEM'
                );



                $sheet->setCellValue(
                    'B3',
                    'LAPORAN DANA MASUK'
                );









                $sheet->getStyle(
                    'B1:E3'
                )
                ->applyFromArray([


                    'font'=>[

                        'bold'=>true

                    ],



                    'alignment'=>[

                        'horizontal'=>Alignment::HORIZONTAL_CENTER,

                        'vertical'=>Alignment::VERTICAL_CENTER

                    ]



                ]);





                $sheet->getStyle('B1')
                ->getFont()
                ->setSize(16);



                $sheet->getStyle('B2')
                ->getFont()
                ->setSize(13);



                $sheet->getStyle('B3')
                ->getFont()
                ->setItalic(true)
                ->setSize(10);









                /*
                SECTION
                */


                $sectionRows=[

                    7

                ];





                foreach($sectionRows as $row){



                    $sheet->mergeCells(
                        'A'.$row.':E'.$row
                    );



                    $sheet->getStyle(
                        'A'.$row.':E'.$row
                    )
                    ->applyFromArray([


                        'fill'=>[

                            'fillType'=>Fill::FILL_SOLID,

                            'startColor'=>[
                                'rgb'=>'000000'
                            ]

                        ],



                        'font'=>[

                            'bold'=>true,

                            'color'=>[
                                'rgb'=>'FFFFFF'
                            ]

                        ],



                        'alignment'=>[

                            'horizontal'=>Alignment::HORIZONTAL_CENTER

                        ]



                    ]);



                }









                /*
                TABLE HEADER
                */


                $sheet->getStyle(
                    'A11:E11'
                )
                ->applyFromArray([



                    'fill'=>[

                        'fillType'=>Fill::FILL_SOLID,

                        'startColor'=>[
                            'rgb'=>'000000'
                        ]

                    ],



                    'font'=>[

                        'bold'=>true,

                        'color'=>[
                            'rgb'=>'FFFFFF'
                        ]

                    ],



                    'alignment'=>[

                        'horizontal'=>Alignment::HORIZONTAL_CENTER

                    ]



                ]);









                $lastRow=$sheet->getHighestRow();








                /*
                BORDER
                */


                $sheet->getStyle(
                    'A7:E'.$lastRow
                )
                ->applyFromArray([


                    'borders'=>[


                        'allBorders'=>[

                            'borderStyle'=>Border::BORDER_THIN,

                            'color'=>[
                                'rgb'=>'D1D5DB'
                            ]

                        ]

                    ]



                ]);









                /*
                RUPIAH
                */


                $sheet->getStyle(
                    'D12:D'.$lastRow
                )
                ->getNumberFormat()
                ->setFormatCode(
                    '"Rp" #,##0'
                );









                /*
                STATUS
                */


                for($i=12;$i<=$lastRow;$i++)
                {


                    $sheet->getStyle(
                        'E'.$i
                    )
                    ->applyFromArray([


                        'font'=>[

                            'bold'=>true,

                            'color'=>[
                                'rgb'=>'15803D'
                            ]

                        ]

                    ]);


                }









                /*
                WIDTH
                */


                $sheet->getColumnDimension('A')
                ->setWidth(18);



                $sheet->getColumnDimension('B')
                ->setWidth(35);



                $sheet->getColumnDimension('C')
                ->setWidth(22);



                $sheet->getColumnDimension('D')
                ->setWidth(22);



                $sheet->getColumnDimension('E')
                ->setWidth(18);









                /*
                HEIGHT
                */


                $sheet->getRowDimension(1)
                ->setRowHeight(45);



                $sheet->getRowDimension(2)
                ->setRowHeight(30);



                $sheet->getRowDimension(3)
                ->setRowHeight(20);





                $sheet->getRowDimension(7)
                ->setRowHeight(25);









                $sheet->freezePane(
                    'A12'
                );


            }


        ];

    }


}